<?php

add_shortcode('row', 'row');
add_shortcode( 'col', 'span' );
add_shortcode( 'collapse', 'collapse' );
add_shortcode('collapse_item', 'citem' );
add_shortcode( 'tabs', 'tabs' );
add_shortcode( 'thead', 'thead' );
add_shortcode( 'tab', 'tab' );
add_shortcode( 'dropdown', 'dropdown' );
add_shortcode( 'tab_contents', 'tcontents' );
add_shortcode( 'tab_content', 'tcontent' );
add_shortcode ('fullscreenenter', 'full_enter');
add_shortcode ('fullscreenexit', 'full_exit');
add_shortcode ('fullimage', 'fullsizeimage');
add_shortcode ('fullimage-slim', 'fullsizeimage_slim');
add_shortcode ('mediumimage-slim', 'mediumsizeimage_slim');
add_shortcode ('threeupcombobig-slim', 'threeupcombo_slim');
add_shortcode ('2up_image', 'img2up');
add_shortcode ('2up_image_slim', 'img2upslim');
add_shortcode ('2up_image_medium', 'img2upmedium');
add_shortcode ('4up_image', 'img4up');
add_shortcode ('4up_image_slim', 'img4upslim');
add_shortcode ('parallax-image', 'parallaximg');
add_shortcode ('blanklines', 'emptylines');
add_shortcode ('2up_image-standard', 'img2up_standard');
add_shortcode ('next-chapter', 'nextchapter');
add_shortcode ('related-story-left', 'related_box_left');
add_shortcode ('related-story-right', 'related_box_right');
add_shortcode ('side-box-right-pro', 'side_box_right_pro');
add_shortcode ('side-box-left-pro', 'side_box_left_pro');
add_shortcode ('two-column-content', 'two_column');
add_shortcode ('sub-tag', 'sub_tag');
add_shortcode ('social-icons', 'social_icons');
add_shortcode ('3verticalrow', 'img3vertical');
add_shortcode ('pquote', 'promquote');
